### PR TITLE
new NB: GALEX mosaic

### PR DESCRIPTION
**Pull request by ttdu**
- [x] Update narrative: tighten prose, fully explain some details
- [x] Update the kinda terrifying 6 "np.zeros" in a row. CLAIRE: I may ping you for assistance on this
- [x] Justify the "brightness matching": makes the mosaic look more coherent, rather than distinct images pasted together
- [x] Make sure DPI is set to 600. There's no need for anything higher, it just takes longer and bloats the file size
- [x] Justify the gaps in the final mosaic: a product of the not-quite-perfect circles

### CODE REVIEW

**Comment by cmurray-astro** [comment]
I made some pretty significant changes to this notebook and the way it works, so before polishing it up, you should have a look and let me know what you think!

**Comment by ttdu** [comment]
@cmurray-astro : Your changes were excellent, Claire. I made some additional simplifications to the code and added more narrative.

**Review by cmurray-astro — APPROVED** [review]
this looks great! I added imports to the intro, but otherwise I think its good to go!

**Comment by ttdu** [comment]
Good catch! My eyes always glaze over the imports section

**Pull request merged**
