### PR TITLE
Added FIMS-SPEAR notebook and MCCM directory structure.

### PR DESCRIPTION
**Pull request by adrianlucy**
- This can and should wait until Monday!
- Do not merge until FIMS-SPEAR public release (tentatively: Tuesday/Wednesday).

Tutorial notebook for FIMS-SPEAR, a MAST Community-Contributed Mission.
Minor questions:
- I left in one thing that PEP8 compliance check complained about: `%matplotlib notebook` for interactive plots. Is this ok / will CI/CD tolerate it? Should probably be ok to comment it out if necessary, it's essential for users who are actually running the notebook but we could just add an instruction to uncomment it.
- Modules that are part of the default python libraries, like `copy` and `os`, don't need to be in requirements.txt, right?  But I did include `IPython` in the requirements.txt which I was a little unsure about.

### CODE REVIEW

**Comment by ttdu** [comment]
I'll look into the matplotlib magic command. I don't think our other Notebooks do this, so I'm not sure how the CI will respond.

Copy and os don't need to be in the requirements file. The rule is generally "assuming a base Python install, provide the minimum requirements to run this NB". We generally exclude the IPython requirement under the (perhaps faulty) assumption that people already have Jupyter running.

**Comment by ttdu** [comment]
Ok two things to address, and then we can merge:

- [ ] You can get the interactive plots in Jupyter Lab without the %matplotlib notebook, and our other Notebooks render without it; let's drop that for now.
- [ ] Notebooks should be in an un-executed state when committed to the repo; otherwise, the repo becomes large and unwieldy

**Comment by adrianlucy** [comment]
The directory part is already there (unless I'm confused?), but I'll work on the other 2 things!

**Comment by adrianlucy** [comment]
Latest commit removes the executed output. As we discussed, leaving "%matplotlib notebook" in for now, and we'll see how it goes.

(Do my eyes deceive me, or does that say "All checks have passed"? I hadn't dared dream.)

_Note: do not merge until release day._

**Review by ttdu — APPROVED** [review]
Awesome! Approved and ready to merge on release day

**Pull request merged**
