### PR TITLE
Astroquery.mast.mast class tutorial

### PR DESCRIPTION
**Pull request by TheRealZoidberg**

### CODE REVIEW

**Comment by TheRealZoidberg** [comment]
Original error on PR from a fork appears to be fixed by updating requirement in CI - New error appearing on check, ERROR: Could not open requirements file: [Errno 2] No such file or directory: ‘notebooks/astroquery/mast_jwst_queries/requirements.txt’ 

Each notebook folder must have a requirements file.

**Comment by ttdu** [comment]
@jaymedina I reviewed parts 1&2 of the tutorial.

I'm confused on part 3: we're re-building the ephemeris table from our original results? I don't understand how this shows that the wildcard search worked. If the original search had missed a result, it wouldn't be in the coordinate list (for row in ephemeris: ) that we use to re-build the table.

**Comment by jaymedina** [comment]
Hi @ttdu , thanks for the narrative updates!

> I'm confused on part 3: we're re-building the ephemeris table from our original results? I don't understand how this shows that the wildcard search worked. If the original search had missed a result, it wouldn't be in the coordinate list (for row in ephemeris: ) that we use to re-build the table.

My bad, that example was supposed to be a cone search, so we would have added the `radius` param to "gather up" any missing coordinates (i.e. observations) that were missed from the original search with `target_name`. So the query should look more like the following: 

```
tables = []

for row in ephemeris:
    ra, dec, t_min = row["ra"], row["dec"], row["t_min"]
    coords = f'{ra} {dec}'
    observations = Observations.query_criteria(coordinates=coords,
                                               radius=1.0*u.deg,
                                               target_name="COMET-67P-CHURYUMOV-GERASIMENK",
                                               instrument_name="ACS/WFC",
                                               t_min=[t_min-1, t_min+1])

    tables.append(observations)
```

But I realize that works under the assumption that the missing coordinates (if any) would be within the general vicinity of the other coordinates, which could just as well not be the case.

Would you suggest removing this last part and just stopping the notebook after plotting the ephemeris data?

**Comment by ttdu** [comment]
@jaymedina Ah, I understand now. So if we missed the Observation the first time, it might still be "nearby" in the sky.

I think we can stop after plotting the ephemeris and say, "just trust us, wildcard totally works". It might be challenging for new users to understand; if you want to keep it, we could make it into an "optional exercise" with solutions.

**Comment by jaymedina** [comment]
> I think we can stop after plotting the ephemeris and say, "just trust us, wildcard totally works". It might be challenging for new users to understand; if you want to keep it, we could make it into an "optional exercise" with solutions.

I'm in favor of stopping after the ephemeris step, also considering how long it takes to run that cell with the reverse engineering example. Might be too much for what it's worth. I'll update the notebook accordingly. Thanks!

**Review by ttdu — APPROVED** [review]

**Pull request closed without merging**
