### PR TITLE
new NB: UV extinction with IUE

### PR DESCRIPTION
**Pull request by ttdu**
To do before merge:
- [x] There's a mismatch in data length: add a note explaining why we trim the data (so they're the same length)
- [x] Explain equation: the LaTeX equation above the cell corresponds poorly with the Extinction function below. Explain the connection
- [x]  Claire: We just... drop negative fluxes. That uh... certainly avoids errors, but does make me concerned about the quality of data.
- [x] Claire: Should data near the edge of the detectors be excluded? It certainly looks funky, but that's a somewhat lacking scientific justification
- [x] Claire: Should we delete the exercise? I kinda think so since it's just "do the same thing on another star"
- [x] Need to add IUE to the missions list.

### CODE REVIEW

**Comment by ttdu** [comment]
@cmurray-astro Ok, polish applied. I make an attempt to explain the equation we see just before creating the extinction plot. If that is free of factual errors / makes sense, please leave an approving review and we'll get this merged!

**Comment by cmurray-astro** [comment]
awesome! I fetched the changes and it looks like there are now two versions of the notebook (one in the "IUE" folder and one in another sub-folder) I'm wondering if I accidentally did this -- but just to double-check, which one is the right one to review?

**Comment by ttdu** [comment]
Hm, that's strange. I only see one NB in the repo, so some weird git things must be happening.

the NB in the sub-folder is the right one to review.

**Review by cmurray-astro — APPROVED** [review]
looks good to me!

**Pull request merged**
